version: "3.7"

services:
  setup:
    image: ${IMAGE_NAME}
    hostname: his-cybersoc-setup
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://${NODE_NAME}:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://${NODE_NAME}:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    networks:
      - siem_net

  logs:
    image: ${IMAGE_NAME}
    hostname: ${NODE_NAME}
    restart: always
    volumes:
      - ${DATA_ES}:/usr/share/elasticsearch/data
      #- ${CONFIG_ES}:/usr/share/elasticsearch/config
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - ${ES_PORT}:9200
      - 9300:9300
    environment:
      - node.name=${NODE_NAME}
      - cluster.initial_master_nodes=${NODE_NAME}
      #- discovery.seed_hosts=""
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=${ES_JAVA_OPTS_ES}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${CPUS_LIMIT_ES}
          memory: ${MEMORY_LIMIT_ES}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - siem_net

  kibana:
    image: his-cybersoc/dashboard:${STACK_VERSION}
    hostname: his-cybersoc-dashboard
    restart: always
    volumes:
      - ${DATA_DASH}:/usr/share/kibana/data
      - ${CONFIG_DASH}:/usr/share/kibana/config
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - ${KIBANA_PORT}:5601
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${CPUS_LIMIT_DASH}
          memory: ${MEMORY_LIMIT_DASH}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - siem_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    hostname: his-cybersoc-logstash
    restart: always
    ports:
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - ${CONFIG_LOGSTASH}/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ${CONFIG_LOGSTASH}/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - "/etc/localtime:/etc/localtime:ro"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${CPUS_LIMIT_LOGSTASH}
          memory: ${MEMORY_LIMIT_LOGSTASH}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - siem_net
networks:
  siem_net:
    external: true
