---
- name: Leave Swarm if have
  shell: "docker swarm leave -f"
  ignore_errors: yes
  failed_when: false

- name: Join the swarm as a worker
  shell: "docker swarm join --token {{ lookup('file', '/tmp/dsm_wt') }} {{ lookup('file', '/tmp/dsm_ip') }}:2377"
  retries: 5
  delay: 5
